name: 'Chromatic Deployment'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build addon
        run: yarn workspace storybook-addon-cookie build

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: ./packages/demo
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          exitOnceUploaded: true
